language: java
jdk:
- oraclejdk8
- oraclejdk9
script: ./gradlew build compileMinJosmVersion && cp -T `find build/libs/*.jar | head -1` "build/libs/mbtiles.jar"
deploy:
  provider: releases
  api_key:
    secure: SVkkBT/z5pXY5ooK8k15AcmgQucNGnS2LNFswKJdwGMCdEaI14BY4i/XL7MIOzBA6YRBNt3yMlqSlAup7u1kl3m/ZqaCm0AEjX99w9Xp6d3orb1ymYkCMPhzdrIQyDj4XJAri6TCpxnGIQ773oxSQx7hzu3AW865lqW1+AryI40=
  file: "dist/mbtiles.jar"
  on:
    tags: true
    jdk: oraclejdk8
    repo: iandees/josm-mbtiles

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9
