language: java
jdk:
- openjdk8
- openjdk9
script: "./gradlew build compileMinJosmVersion"
deploy:
  provider: releases
  skip_cleanup: 'true'
  api_key:
    secure: fjKUUKiFwKCMhHk9FQg4PFvBDBXo+YBbDcXPPgeSfxHj6LQsaGx3OsWEviprDh6JHoQK2DVJE2SOZLKL5nMd6pO4743x2kQrNwL2133TlTNbO4rpkA2WUTryE25GmUEtDnaS00D1pfuyfg/XnosJAizIhoGtP4qMChZ1lvnpR6k=
  file:
    - "build/dist/mbtiles.jar"
    - "build/tmp/jar/MANIFEST.MF"
  on:
    tags: true
    jdk: openjdk8
    repo: iandees/josm-mbtiles
matrix:
  fast_finish: true
  allow_failures:
  - jdk: openjdk9
